apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-scheduler-app
  labels:
    app: spring-boot-scheduler-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-scheduler-app
  template:
    metadata:
      labels:
        app: spring-boot-scheduler-app
    spec:
      containers:
        - name: spring-boot-scheduler-app
          image: Nrapendra786/argocd:2
          ports:
            - containerPort: 8080