apiVersion: v1
kind: Service
metadata:
  name: spring-boot-scheduler-app-servics
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: spring-boot-scheduler-app